import type { NextPage } from 'next'
import Head from 'next/head'
import prismaClient from '../../prisma/client'
import { Tours } from '@prisma/client'



export async function getServerSideProps() {
    const list = await prismaClient.tours.findMany()
    list.map(item => {
        item.time = item.time.toDateString() as any
        return item
    })
    return {
      props: {list},
    }
}

const Page: NextPage<{list:Tours[]}> = ({list}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='m-auto w-2/5 md:bg-gray-700 md:dark:bg-gray-800 p-4 rounded-lg shadow-lg'>
        <ul>
            {list.map(item => <li className='text-white' key={item.id}>ID: {item.id}, Name: {item.name}, DateTime: {item.time.toString()}</li>)}
        </ul>
      </div>
    </div>
  )
}

export default Page